language: julia
sudo: required

julia:
  - 1.5
dist: xenial

addons:
  apt:
    packages:
      - libhdf5-serial-dev

branches:
  only:
    - master
    - travis

before_script:
  - julia -e "using Pkg; Pkg.add(PackageSpec(url=\"https://github.com/kleinhenz/Keldysh.jl.git\", rev=\"v0.6.1\"))"
  - julia -e "using Pkg; Pkg.add(\"HDF5\")"
  - julia -e "using Pkg; Pkg.add(\"ArgParse\")"
