name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          - '1.6'

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - name: Install Keldysh.jl
        run: julia --project -e "using Pkg; Pkg.add(PackageSpec(url=\"https://github.com/kleinhenz/Keldysh.jl.git\", rev=\"v0.6.1\"))"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
